# Generated by Django 5.0.7 on 2024-09-30 04:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='wachlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='Listingwachlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
